import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.SUPABASE_URL
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!supabaseUrl || !supabaseKey) {
  throw new Error(
    'Missing Supabase env vars. ' +
    'Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in api/.env.local'
  )
}

// Use the service-role key server-side so Row Level Security is bypassed
// for INSERT operations from this trusted API layer.
export const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: { persistSession: false },
})

// ── Typed row ──────────────────────────────────────────────────────────────
export interface EventQuote {
  id?:          string       // uuid – auto-generated by Postgres
  client_name:  string
  client_phone: string
  event_type:   string
  event_date:   string | null
  guest_count:  number | null
  notes:        string | null
  created_at?:  string       // timestamptz – auto-generated by Postgres
}
